# Generated by Django 3.2.9 on 2021-11-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='agency_pics')),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
