# Generated by Django 3.2.9 on 2021-11-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image',models.ImageField(upload_to='gallery')),
                ('overview', models.TextField()),
                ('year', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                
            ],
        ),
    ]
